
    # –Ω–∞–∑–≤–∞–Ω–∏–µ
name: Project test

# —Ü–µ–ª–µ–≤—ã–µ —Å–æ–±—ã—Ç–∏—è –¥–ª—è –∑–∞–ø—É—Å–∫–∞
# –≤ –¥–∞–Ω–Ω–æ–º —Å–ª—É—á–∞–µ —ç—Ç–æ push –∏ pull_request, –≤ –≤–µ—Ç–∫—É master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# –≤—ã–ø–æ–ª–Ω—è–µ–º—ã–µ –¥–µ–π—Å—Ç–≤–∏—è
jobs:
  Runs-tests:
    runs-on: ubuntu-latest
    
    # –∑–∞–ø—É—Å–∫–∞—é—Ç—Å—è –ø–æ —à–∞–≥–∞–º
    # name - –Ω–∞–∑–≤–∞–Ω–∏–µ —à–∞–≥–∞
    # –≤ github actions –±—É–¥–µ—Ç –≤—ã–≤–æ–¥–∏—Ç—å—Å—è –Ω–∞–∑–≤–∞–Ω–∏–µ —à–∞–≥–∞, –∏ –ø—Ä–æ—Ü–µ—Å—Å—ã
    steps:
          - uses: actions/checkout@v3
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
                 python-version: '3.x'
          - name: Install dependencies üîß
            run: |
                   python -m pip install --upgrade pip
                   pip install -r requirements.txt
          - name: Test with pytest üî®
            run: |
                   pytest tests/test_LandingPage.py 
          
      
